[project]
name = "peda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Werner van der Merwe", email = "wvdm1217@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.12.5",
]

[project.scripts]
peda = "peda:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
